services:
  mesh-test-db:
    image: postgres:latest
    container_name: mesh-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mesh
    ports:
      - "7000:5432"

  mesh-test-api:
    image: maven:3.8.6-openjdk-17-slim
    container_name: mesh-test-api
    depends_on:
      - mesh-test-db
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mesh-test-db:5432/mesh
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    command: java -jar todo.jar
