version: '3.8'

services:
  mesh-test-db:
    image: postgres:latest
    container_name: mesh-test-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${dbPassword}
      - POSTGRES_DB=mesh
    ports:
      - 7000:5432
